[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "fanuc-opcua"
version = "0.1.0"
description = "An easy to use Python OPC UA client library specifically for Fanuc robot controllers."
readme = "README.md"
authors = [
    {name = "Nikhil Kumar"}
]
requires-python = ">=3.8"
dependencies = [
    "asyncua>=1.0.5"
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "pytest-asyncio>=0.21.0"
]

[tool.setuptools.packages.find]
include = ["fanuc_opcua*"]
